on: push
name: Publish
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: install
      with:
        entrypoint: npm
        args: ci --production
    - name: build
      with:
        entrypoint: npm
        args: run build
    - name: push
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        entrypoint: npm
        args: run push
